### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by FabioZTessitore** [TeoColuccio/exp#1]
il gitignore non filtra i file oggetto

**Comment by TeoColuccio** [comment]
Aggiustato

**Comment by FabioZTessitore** [comment]
non è vero

**Comment by TeoColuccio** [comment]
Cosa si dovrebbe inserire oltre *.o e i nomi degli eseguibili compilati dal make?

**Comment by TeoColuccio** [comment]
Infatti.. ne mancava uno, ma degli eseguibili
