### ISSUE TITLE
makefile

### ISSUE THREAD

**Issue by FabioZTessitore** [TeoColuccio/exp#2]
che fai, aggiungi la libreria matematica così? ci sono programmi che non ne hanno bisogno

**Comment by TeoColuccio** [comment]
Lo so, ma nel paragrafo del Makefile non c'è scritto come linkare una libreria solo per un file..

**Comment by FabioZTessitore** [comment]
infatti non c'è scritto. Ecco la procedura dettagliata:

1. mettere in una sottodirectory

**Comment by TeoColuccio** [comment]
E poi?

**Comment by FabioZTessitore** [comment]
quella è la procedura
